
######################## default configuration ####################
baseURL = "https://icphublatam.org"
title = "Nativo Cripto"
enableRobotsTXT = true
DefaultContentLanguage = "es"

theme = "dd4w"
# post pagination
paginate = "8"

# Este es el de google tag manager
googleAnalytics = ""

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"

# JS Plugins
[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"
[[params.plugins.js]]
link="https://kit.fontawesome.com/a6f10b653b.js"

############################## navigation ###############################
[menu]


  #[[menu.main]]
  #name = "FAQ"
  #URL = "/faq"
  #weight = 6



#################### default parameters ################################
[params]
logo = "/images/logo-monochrome.svg"
home = "Home"

# Meta data
description = "Certificaciones, bootcamps y cursos de blockchain intensivos para impulsar tu carrera profesional y posicionarte como un referente."
images = ["/images/blog/.jpg"]
twitter_user = "@icphublatam"
email = "hola@icphublatam.org"
author = "ICP Hub Latam"



# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Unirte ahora"
link = "#"


############################# social icon ############################










